# Generated by Django 5.2.8 on 2025-11-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursal', '0004_alter_sucursal_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('admin', models.CharField(choices=[('ADM', 'Administrador'), ('CAJ', 'Cajero')], default='CAJ', max_length=3)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='sucursal.empleado')),
            ],
        ),
    ]
