# Generated by Django 5.2.8 on 2025-11-05 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField(unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(default='')),
                ('mail', models.CharField(max_length=50)),
                ('cargo', models.CharField(choices=[('GER', 'Gerente'), ('EMP', 'Empleado')], max_length=3)),
                ('contratoPrincipio', models.DateField()),
                ('contratoFin', models.DateField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Empleados', to='sucursal.sucursal')),
            ],
        ),
    ]
