# Generated by Django 5.2.8 on 2025-11-05 20:00

import sucursal.validaciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=20, validators=[sucursal.validaciones.pedir_nombre_hasta_valido]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.IntegerField(unique=True, validators=[sucursal.validaciones.pedir_dni_hasta_valido]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='mail',
            field=models.CharField(max_length=50, validators=[sucursal.validaciones.pedir_telefono_hasta_valido]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=20, validators=[sucursal.validaciones.pedir_nombre_hasta_valido]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(default='', validators=[sucursal.validaciones.pedir_telefono_hasta_valido]),
        ),
    ]
