# Generated by Django 5.2.8 on 2025-11-06 23:45

import sucursal.validaciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='mail',
            field=models.CharField(max_length=50, validators=[sucursal.validaciones.pedir_mail_hasta_valido]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(blank=True, validators=[sucursal.validaciones.pedir_telefono_hasta_valido]),
        ),
    ]
