# Generated by Django 5.2.8 on 2025-11-06 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='name',
            field=models.CharField(default='Catalogo', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategoria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Producto', to='products.subcategoriaproducto'),
        ),
        migrations.AlterField(
            model_name='subcategoriaproducto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Subcategoria', to='products.categoriaproducto'),
        ),
    ]
