# Generated by Django 5.2.8 on 2025-11-16 16:07

import sucursal.validaciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0002_alter_empleado_mail_alter_empleado_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='mail',
            field=models.EmailField(max_length=50, validators=[sucursal.validaciones.pedir_mail_hasta_valido]),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='contacto',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='provincia',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
