# Generated by Django 5.2.8 on 2025-11-16 16:38

import sucursal.validaciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0003_sucursal_mail_alter_empleado_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='mail',
            field=models.EmailField(max_length=254, validators=[sucursal.validaciones.pedir_mail_hasta_valido]),
        ),
    ]
