# Generated by Django 5.2.7 on 2025-11-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0004_alter_sucursal_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='contacto',
            field=models.IntegerField(),
        ),
    ]
