# Generated by Django 5.2.8 on 2025-11-05 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('sucursal', '0002_alter_empleado_apellido_alter_empleado_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('dni', models.IntegerField(blank=True)),
                ('metodo_pago', models.CharField(choices=[('EFE', 'Efectivo'), ('CRE', 'Credito'), ('DEB', 'Debito'), ('TRA', 'Transferencia')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='pagodetalle',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='pagodetalle',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='numero',
        ),
        migrations.AddField(
            model_name='caja',
            name='empleado',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sucursal.empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activa'), ('CER', 'Cerrada')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='numeroCaja',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('caja', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.caja')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='PagoDetalle',
        ),
    ]
