# Generated by Django 5.2.8 on 2025-11-06 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.caja'),
        ),
    ]
