# Generated by Django 5.2.7 on 2025-11-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_catalogo_name_alter_product_subcategoria_and_more'),
        ('sales', '0003_alter_venta_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('CRE', 'Credito'), ('DEB', 'Debito'), ('TRA', 'Transferencia')], default='EFE', max_length=3),
        ),
        migrations.AlterField(
            model_name='caja',
            name='numeroCaja',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.caja'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.venta')),
            ],
        ),
    ]
