# Generated by Django 5.2.7 on 2025-12-03 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_product_categoria_alter_product_codigo_and_more'),
        ('sucursal', '0005_alter_sucursal_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('dni', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCaja', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('apertura', models.TimeField(blank=True, null=True)),
                ('cierre', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('CER', 'Cerrada')], max_length=3)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='sucursal.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.IntegerField(blank=True, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFE', 'Efectivo'), ('CRE', 'Credito'), ('DEB', 'Debito'), ('TRA', 'Transferencia')], default='EFE', max_length=3)),
                ('estado_venta', models.CharField(choices=[('FIN', 'Finalizada'), ('PRC', 'En proceso'), ('PEN', 'Pendiente')], default='PEN', max_length=3)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.caja')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.IntegerField(blank=True, default=0, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.venta')),
            ],
        ),
    ]
