# Generated by Django 5.2.8 on 2025-11-13 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_cliente_metodo_pago_venta_metodo_pago_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='price',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='metodo_pago',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('CRE', 'Credito'), ('DEB', 'Debito'), ('TRA', 'Transferencia')], default='EFE', max_length=3),
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
