# Generated by Django 5.2.8 on 2025-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_price_detalleventa_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='total',
            new_name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='price',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
