# Generated by Django 5.2.8 on 2025-11-15 13:54

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_total_detalleventa_precio_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
