# Generated by Django 5.2.8 on 2025-11-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_venta_fecha_detalleventa_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='fecha',
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
