# Generated by Django 5.2.8 on 2025-11-16 15:39

from django.db import migrations, models

def generar_numeros_venta(apps, schema_editor):
    Venta = apps.get_model('sales', 'Venta')
    for index, venta in enumerate(Venta.objects.all().order_by('id'), start=1):
        venta.numero_venta = index
        venta.save()
class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_detalleventa_fecha_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_venta',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
