# Generated by Django 5.2.8 on 2025-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_detalleventa_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
