# Generated by Django 5.2.8 on 2025-11-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_cliente_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pago',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
