# Generated by Django 5.2.8 on 2025-11-18 17:13

from django.db import migrations, models
from datetime import time

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_remove_cliente_pago_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=time(0,0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
