# Generated by Django 5.2.8 on 2025-11-18 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_venta_hora_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='hora',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
