# Generated by Django 5.2.8 on 2025-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_venta_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
