# Generated by Django 5.2.7 on 2025-11-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_venta_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_venta',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
