# Generated by Django 5.2.8 on 2025-11-21 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_venta_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_venta',
            field=models.CharField(choices=[('FIN', 'Finalizada'), ('PRC', 'En proceso'), ('PEN', 'Pendiente')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_venta',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
