# Generated by Django 5.2.8 on 2025-11-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_venta_estado_venta_alter_venta_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2, null=True),
        ),
    ]
