# Generated by Django 5.2.8 on 2025-11-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_detalleventa_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='descuento',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
