# Generated by Django 5.2.8 on 2025-11-25 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_detalleventa_descuento'),
        ('sucursal', '0004_alter_sucursal_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sucursal.empleado'),
        ),
    ]
