# Generated by Django 5.2.7 on 2025-11-25 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_detalleventa_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
