# Generated by Django 5.2.8 on 2025-11-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_caja_apertura_caja_cierre_caja_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='numeroCaja',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
