# Generated by Django 5.2.8 on 2025-11-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_caja_numerocaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='historial_cierres',
            field=models.JSONField(default=list),
        ),
    ]
