# Generated by Django 5.2.8 on 2025-11-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_catalogo_name_alter_product_subcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='products.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategoria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='products.subcategoriaproducto'),
        ),
    ]
